[project]
name = "Todo_Backend"
version = "0.1.0"
description = "Backend for Todo application with CRUD Operations."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
]
